export const projects = [
  {
    title: 'My Notes',
    description: "A collection of all my notes from self-teaching myself how to code!",
    image: '/images/Notes.png',
    tags: ['GoogleDoc'],
    source: 'https://docs.google.com/document/d/12V8XKiNlYWjSapwMeIiz9Drb-KvsYWzMmQf0JmpfwWk/edit?usp=sharing',
    visit: 'https://docs.google.com/document/d/12V8XKiNlYWjSapwMeIiz9Drb-KvsYWzMmQf0JmpfwWk/edit?usp=sharing',
    id: 0,
  },
  {
    title: 'seeded',
    description: "A group project where we built a social media platform for people to share plants.",
    image: '/images/seeded.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'MySQL'],
    source: 'https://seed-ed.herokuapp.com/',
    visit: 'https://github.com/sabhanson/seeded',
    id: 1,
  },
  // {
  //   title: 'Arcade Sweet',
  //   description: "An online arcade where you can play Wordle and Card Matching.",
  //   image: '/images/3.jpg',
  //   tags: ['React', 'MongoDB', 'Mongoose', 'JavaScript'],
  //   source: 'https://asweet-front.herokuapp.com/',
  //   visit: 'https://github.com/sabhanson/arcade-sweet-front',
  //   id: 2,
  // },
  {
    title: 'My First Website',
    description: "The very first website I made before starting my coding bootcamp!",
    image: '/images/Fanpage.png',
    tags: ['HTML', 'CSS'],
    source: 'https://425megs.github.io/Fanpage/',
    visit: 'https://github.com/425megs/Fanpage',
    id: 2,
  },
  {
    title: 'Password Generator',
    description: "This generator can create a complex password based on selected criteria.",
    image: '/images/Password.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://425megs.github.io/Password-Gen/',
    visit: 'https://github.com/425megs/Password-Gen',
    id: 3,
  },
  // {
  //   title: 'README Generator',
  //   description: "A tool I created to auto-generate READMEs for my projects. Clone to use.",
  //   image: '/images/READMEgen.png',
  //   tags: ['JavaScript', 'Node.js'],
  //   source: 'https://github.com/425megs/README-Generator',
  //   visit: 'https://github.com/425megs/README-Generator',
  //   id: 5,
  // },
];